---
abstract: 'Use a Perl 5 group of modules/features'
author:
  - 'Ingy döt Net <ingy@ingy.net>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: perl5
name: perl5
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.10.0
  version: 0.99
resources:
  homepage: https://github.com/ingydotnet/perl5-pm/tree
  license: http://dev.perl.org/licenses/
  repository:
    type: git
    url: git://github.com/ingydotnet/perl5-pm.git
    web: https://github.com/ingydotnet/perl5-pm/tree
version: 0.09
