---
abstract: 'Use a Perl 5 group of modules/features'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires:
  Module::Runtime: '0'
  Sub::Exporter: '0'
  Test::Exception: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: perl5
no_index:
  directory:
    - inc
    - t
    - xt
    - example
requires:
  perl: v5.8.1
  version: '0.99'
resources:
  bugtracker: https://github.com/ingydotnet/perl5-pm/issues
  homepage: https://github.com/ingydotnet/perl5-pm
  repository: https://github.com/ingydotnet/perl5-pm.git
version: '0.19'
