---
abstract: 'Use a Perl 5 group of modules/features'
author:
  - 'Ingy döt Net <ingy@ingy.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: perl5
name: perl5
no_index:
  directory:
    - inc
    - t
requires:
  Hook::LexWrap: 0.24
  perl: 5.10.0
  version: 0.77
resources:
  homepage: http://github.com/ingydotnet/perl5-pm/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/ingydotnet/perl5-pm.git
version: 0.08
